#!/bin/bash

# GLOBALS
USAGE="Usage: `basename $0` <init|vim|cleanup>"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# CONFIG
name='Edward'

if [ ! -n "$1" ]
then
  echo $USAGE
  return
fi

if [ "init" = "$1" ]
then
  alias edify=". $DIR/edify"
  echo "Created alias edify"
  mkdir -p $DIR/tmp
  echo "Created tmp directory"
  return
fi

if [ "vim" = "$1" ]
then
  # check for dependencies: vim
  hash vim 2>/dev/null || { echo >&2 "Vim is not installed."; return; }

  mkdir -p $DIR/tmp/vim/
  # move original .vim* files to tmp/
  cp -r ~/.vim* $DIR/tmp/vim/

  cp -r $DIR/config/vim/.vim* ~

  # might need to get vundle
  mkdir ~/.vim/bundle/
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle


  # bundle install vim plugins
  vim +BundleInstall +qall

  touch ~/.vim/.edified

  echo "Welcome $name..."
  echo 'To restore original config: edify cleanup'
fi

if [ "cleanup" = "$1" ]
then
  # check the existance of the .edified file
  if [ ! -f ~/.vim/.edified ]
  then
    echo "System is not edified."
    return
  else
    rm -rf ~/.vim
    cp -r $DIR/tmp/vim/.vim* ~
    echo "Files are restored to their original location"
    echo "Deleting .edify folder"
    rm -rf $DIR
    echo "Unaliasing edify command"
    unalias edify
    echo "Goodbye $name..."
    return
  fi
fi

return
